spring.application.name=helpdesk-api
server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:helpdesk
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
